global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: core-service
    metrics_path: /monitor/core-service
    static_configs:
      - targets:
          - core-service:8080
  - job_name: auth-service
    metrics_path: /monitor/auth-service
    static_configs:
      - targets:
        - auth-service:3001
  - job_name: storage-service
    metrics_path: /monitor/storage-service
    static_configs:
      - targets:
        - storage-service:3002
  - job_name: telegraf
    scrape_interval: 15s
    static_configs:
      - targets: [ 'telegraf:9100' ]