global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: core-service-monitoring
    metrics_path: /monitor/core-service
    static_configs:
      - targets:
          - core-service:3000
  - job_name: telegraf
    scrape_interval: 15s
    static_configs:
      - targets: [ 'telegraf:9100' ]